stages:
- build 
# - test

build_MR:
  stage: build
  tags:
    - docker
  image: 
    name: gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


build_main:
  stage: build
  tags:
    - docker 
  image:
    name:  gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [ "" ]
  script: 
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}"
      --dockerfile "Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules: 
    - if: $CI_COMMIT_BRANCH == "main" 
