"""add new columns

Revision ID: d967605014ce
Revises: 
Create Date: 2025-05-23 11:34:52.404919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd967605014ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('postcode', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('picture_thumbnail', sa.String(length=200), nullable=True))
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=False)
    op.drop_column('users', 'picture_thumbnail')
    op.drop_column('users', 'postcode')
    op.drop_column('users', 'country')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
